name: supervisely-app-release
run-name: Supervisely ${{ github.repository }} app release
on:
  workflow_call:
    inputs:
      SUPERVISELY_SERVER_ADDRESS:
        required: true
        type: string
      SUPERVISELY_PROD_SERVER_ADDRESS:
        required: true
        type: string
      SLUG:
        required: true
        type: string
      RELEASE_VERSION:
        required: true
        type: string
      RELEASE_DESCRIPTION:
        required: true
        type: string
    secrets:
      SUPERVISELY_DEV_API_TOKEN:
        required: true
      SUPERVISELY_PRIVATE_DEV_API_TOKEN:
        required: true
      SUPERVISELY_PROD_API_TOKEN:
        required: true
      GH_ACCESS_TOKEN:
        required: true
      

jobs:
  Supervisely-Release:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_TYPE: ${{ steps.update_app_config.outputs.RELEASE_TYPE }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Update App Config
        id: update_app_config
        run: |
          VERSION="${{ inputs.RELEASE_VERSION }}"
          if [[ $VERSION == v* ]]; then
            VERSION="${VERSION:1}"
          fi
          echo "DOCKER_IMAGE=$VERSION" >> $GITHUB_ENV
          
          SEMVER_REGEX="^[0-9]+\.[0-9]+\.[0-9]+$"
          if [[ ! $VERSION =~ $SEMVER_REGEX ]]; then
          RELEASE_TYPE = "release-branch"
          else
          RELEASE_TYPE = "release"
          fi
          echo "RELEASE_TYPE=$RELEASE_TYPE" >> $GITHUB_OUTPUT
          
          python .github/workflows/agent_app/update_config.py
          echo "docker_image set to $VERSION"

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .github/workflows/agent_app/config.json
          git commit -m "Update config for release $VERSION"
          git push

  Release:
    needs: Supervisely-Release
    uses: supervisely-ecosystem/workflows/.github/workflows/common.yml@master
    secrets:
      SUPERVISELY_DEV_API_TOKEN: "${{ secrets.SUPERVISELY_DEV_API_TOKEN }}"
      SUPERVISELY_PRIVATE_DEV_API_TOKEN: "${{ secrets.SUPERVISELY_PRIVATE_DEV_API_TOKEN }}"
      SUPERVISELY_PROD_API_TOKEN: "${{ secrets.SUPERVISELY_PROD_API_TOKEN }}"
      GH_ACCESS_TOKEN: "${{ secrets.GH_ACCESS_TOKEN }}"
    with:
      SUPERVISELY_SERVER_ADDRESS: "${{ inputs.SUPERVISELY_SERVER_ADDRESS }}"
      SUPERVISELY_PROD_SERVER_ADDRESS: "${{ inputs.SUPERVISELY_PROD_SERVER_ADDRESS }}"
      SLUG: "${{ inputs.SLUG }}"
      RELEASE_VERSION: "${{ inputs.RELEASE_VERSION }}"
      RELEASE_DESCRIPTION: "${{ inputs.RELEASE_DESCRIPTION }}"
      RELEASE_TYPE: "${{ needs.Supervisely-Release.outputs.RELEASE_TYPE }}"
      SUBAPP_PATHS: ".github/workflows/agent_app"
      SKIP_INSTANCE_VERSION_VALIDATION: "true"
      SKIP_IMAGE_VALIDATION: "true"
