name: Supervisely release
run-name: Supervisely ${{ github.repository }} app release
on:
  workflow_call:
    inputs:
      SUPERVISELY_SERVER_ADDRESS:
        required: true
        type: string
      SUPERVISELY_PROD_SERVER_ADDRESS:
        required: true
        type: string
      SLUG:
        required: true
        type: string
      RELEASE_VERSION:
        required: true
        type: string
      RELEASE_DESCRIPTION:
        required: true
        type: string
    secrets:
      SUPERVISELY_DEV_API_TOKEN:
        required: true
      SUPERVISELY_PRIVATE_DEV_API_TOKEN:
        required: true
      SUPERVISELY_PROD_API_TOKEN:
        required: true
      GH_ACCESS_TOKEN:
        required: true
      

jobs:
  Supervisely-Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Update App Config
        run: |
          VERSION="${{ inputs.RELEASE_VERSION }}"
          if [[ $VERSION == v* ]]; then
            VERSION="${VERSION:1}"
          fi
          echo "DOCKER_IMAGE=$VERSION" >> $GITHUB_ENV
          echo "DOCKER_IMAGE set to $VERSION"
          
          SEMVER_REGEX="^[0-9]+\.[0-9]+\.[0-9]+$"
          if [[ ! $VERSION =~ $SEMVER_REGEX ]]; then
          RELEASE_TYPE = "release-branch"
          else
          RELEASE_TYPE = "release"
          fi
          echo "RELEASE_TYPE=$RELEASE_TYPE" >> $GITHUB_ENV
          
          python .github/workflows/agent_app/update_config.py

      - name: Supervisely Release
        uses: supervisely-ecosystem/workflows/.github/workflows/common.yml@master
        env:
          DEV_SERVER_ADDRESS: "${{ inputs.SUPERVISELY_SERVER_ADDRESS }}"
          PROD_SERVER_ADDRESS: "${{ inputs.SUPERVISELY_PROD_SERVER_ADDRESS }}"
          DEV_API_TOKEN: "${{ secrets.SUPERVISELY_DEV_API_TOKEN }}"
          PRIVATE_DEV_API_TOKEN: "${{ secrets.SUPERVISELY_PRIVATE_DEV_API_TOKEN }}"
          PROD_API_TOKEN: "${{ secrets.SUPERVISELY_PROD_API_TOKEN }}"
          GH_ACCESS_TOKEN: "${{ secrets.GH_ACCESS_TOKEN }}"
          SLUG: "${{ inputs.SLUG }}"
          RELEASE_VERSION: "${{ inputs.RELEASE_VERSION }}"
          RELEASE_DESCRIPTION: "${{ inputs.RELEASE_DESCRIPTION }}"
          RELEASE_TYPE: "${{ env.RELEASE_TYPE }}"
          SUBAPP_PATHS: ".github/workflows/agent_app"
          SKIP_INSTANCE_VERSION_VALIDATION: "true"
          SKIP_IMAGE_VALIDATION: "true"
