name: manual-app-release

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: "App Version"
        required: true
        default: ""
      release_description:
        description: "Release Description"
        required: true
        default: "Manual Agent App release"
      publish:
        description: "Publish app"
        required: false
        type: boolean
        default: false

jobs:
  Release-Agent-App:
    permissions:
      contents: write
      actions: write
    uses: supervisely/agent/.github/workflows/app-release.yml@app-release
    secrets:
      SUPERVISELY_DEV_API_TOKEN: "${{ secrets.SUPERVISELY_DEV_API_TOKEN }}"
      SUPERVISELY_PRIVATE_DEV_API_TOKEN: "${{ secrets.SUPERVISELY_PRIVATE_DEV_API_TOKEN }}"
      SUPERVISELY_PROD_API_TOKEN: "${{ secrets.SUPERVISELY_PROD_API_TOKEN }}"
      GH_ACCESS_TOKEN: "${{ secrets.SUPERVISELY_GITHUB_ACCESS_TOKEN }}"
    with:
      SUPERVISELY_SERVER_ADDRESS: "${{ vars.SUPERVISELY_DEV_SERVER_ADDRESS }}"
      SUPERVISELY_PROD_SERVER_ADDRESS: "${{ vars.SUPERVISELY_PROD_SERVER_ADDRESS }}"
      SLUG: "${{ github.repository }}"
      RELEASE_VERSION: "${{ inputs.tag_version }}"
      RELEASE_DESCRIPTION: "${{ inputs.release_description }}"
      PUBLISH: "${{ inputs.publish }}"
