name: Developer version

# https://stackoverflow.com/questions/59429622/user-input-in-github-actions-specify-repo-branch-etc

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Define branch name'
        required: true
        default: 'master'


jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: supervisely/base-py-sdk
        tags: ${{ env.RELEASE_VERSION }}
        addLatest: true
        dockerfile: "base_images/py_sdk/Dockerfile"
        registry: docker.io
        buildArgs: |
          tag_ref_name=${{ env.RELEASE_VERSION }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
